### PR TITLE
hand_drawn implementation

### PR DESCRIPTION
**Pull request by Iagea**
randepict.py even bigger

### CODE REVIEW

**Review by OBrink — APPROVED** [review]

**Comment by OBrink** [comment]
@Iagea:
The linter has the following complaints:
./RanDepict/randepict.py:36:1: F811 redefinition of unused 'Image' from line 8
./RanDepict/randepict.py:279:15: F821 undefined name 'rotate'
./RanDepict/randepict.py:467:14: E225 missing whitespace around operator
./RanDepict/randepict.py:473:14: E225 missing whitespace around operator
./RanDepict/randepict.py:622:9: F841 local variable 'num_salt' is assigned to but never used
./RanDepict/randepict.py:625:13: E741 ambiguous variable name 'l'
./RanDepict/randepict.py:627:56: E231 missing whitespace after ','
./RanDepict/randepict.py:631:9: F841 local variable 'num_pepper' is assigned to but never used
./RanDepict/randepict.py:634:13: E741 ambiguous variable name 'l'
./RanDepict/randepict.py:636:56: E231 missing whitespace after ','
./RanDepict/randepict.py:1343:63: E231 missing whitespace after ','

**Comment by OBrink** [comment]
@Iagea 
./RanDepict/randepict.py:8:69: W291 trailing whitespace
./RanDepict/randepict.py:278:15: F821 undefined name 'rotate'
./RanDepict/randepict.py:621:9: F841 local variable 'num_salt' is assigned to but never used
./RanDepict/randepict.py:625:28: F821 undefined name 'nun_salt'
./RanDepict/randepict.py:627:49: W291 trailing whitespace
./RanDepict/randepict.py:636:49: W291 trailing whitespace

**Comment by OBrink** [comment]
@Iagea 
./RanDepict/randepict.py:278:15: F821 undefined name 'rotate'

**Comment by OBrink** [comment]
@Iagea: Are you using a linter in your IDE?
./RanDepict/randepict.py:307:10: E999 IndentationError: expected an indented block after function definition on line 304

**Comment by Iagea** [comment]
I just did and updated, once more, the randepict.py file. Now flake8 only shows the "W605 invalid escape sequence" and the "W503 line break before binary operator" errors.

**Pull request merged**
